SELECT FICHENO, SUM(UNITPRICE) AS TOTAL_PRICE,
CASE
	WHEN SUM(UNITPRICE) <= 6000 THEN 'LOW'
	WHEN SUM(UNITPRICE) < 12000 THEN 'MEDIUM'
	ELSE 'HIGH'
END AS PRICE_TEXT
FROM ORDERLINE ORL
JOIN ORDERFICHE ORF ON ORF.ID = ORL.ORDERFICHEID
GROUP BY FICHENO
