CREATE TABLE PRICE_LOG (
    LOG_ID INT IDENTITY(1,1) PRIMARY KEY,
    ITEMS_ID INT,
    OLD_PRICE INT,
    NEW_PRICE INT,
    updated_at DATETIME DEFAULT GETDATE()
);

CREATE TRIGGER UPDATE_PRICE_QUANTITY
ON ITEMS
AFTER UPDATE
AS
BEGIN
	IF UPDATE(PRICE)
	BEGIN
	INSERT INTO PRICE_LOG (ITEMS_ID, OLD_PRICE, NEW_PRICE)
	SELECT
		i.ID,
		d.PRICE AS OLD_PRICE,
		i.PRICE AS NEW_PRICE
	FROM inserted i
	JOIN deleted d ON i.ID = d.ID
	END
END;