WITH CITY_AVG AS (
SELECT CUS.NAMESURNAME, ADR.CITY,ORF.NETTOTAL,
ROW_NUMBER() OVER (PARTITION BY ADR.CITY ORDER BY ORF.NETTOTAL DESC) AS rank_
FROM ORDERFICHE ORF
JOIN CUSTOMER CUS ON CUS.ID = ORF.CUSTOMERID
JOIN ADDRESS ADR ON ADR.ID = ORF.ADDRESSID)
SELECT * FROM CITY_AVG
WHERE rank_ = 1