SELECT CUS.NAMESURNAME, FICHENO, DATE_, ORL.NETTOTAL, 
CASE 
	WHEN DATEPART(WEEKDAY, DATE_) > 5
	THEN 'Weekend'
	ELSE 'Mid-week'
END AS WEEK_QUERY
FROM ORDERLINE ORL
JOIN ORDERFICHE ORF ON ORF.ID = ORL.ORDERFICHEID
JOIN CUSTOMER CUS ON CUS.ID = ORF.CUSTOMERID